import 'package:flutter/material.dart';
import 'workspace_controller.dart';
import 'workspace_models.dart';

class _OpsPage extends StatelessWidget {const _OpsPage({required this.eyebrow,required this.title,required this.subtitle,required this.children});final String eyebrow,title,subtitle;final List<Widget> children;@override Widget build(BuildContext context)=>ColoredBox(color:const Color(0xFFF3F5F6),child:ListView(padding:const EdgeInsets.fromLTRB(24,18,24,28),children:[const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('9:41',style:_small),Text('5G  100%',style:_small)]),const SizedBox(height:12),Text(eyebrow.toUpperCase(),style:_eyebrow),const SizedBox(height:12),Text(title,style:_title),const SizedBox(height:12),Text(subtitle,style:const TextStyle(fontSize:13,color:Color(0xFF667980))),const SizedBox(height:12),...children]));}
class _Panel extends StatelessWidget {const _Panel(this.title,this.subtitle,this.status,{this.statusColor=const Color(0xFF667980),this.onTap});final String title,subtitle,status;final Color statusColor;final VoidCallback? onTap;@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Material(color:Colors.white,borderRadius:BorderRadius.circular(8),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(8),child:Container(minHeight:86,padding:const EdgeInsets.all(14),decoration:BoxDecoration(border:Border.all(color:const Color(0xFFD8E0E3)),borderRadius:BorderRadius.circular(8)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w600,color:Color(0xFF172026))),const SizedBox(height:6),Text(subtitle,maxLines:1,overflow:TextOverflow.ellipsis,style:_small),const SizedBox(height:6),Text(status,style:TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:statusColor))])))));}

class FigmaApprovalsScreen extends StatelessWidget {const FigmaApprovalsScreen({super.key,required this.controller});final WorkspaceController controller;@override Widget build(BuildContext context){final pending=controller.pendingApprovals;return _OpsPage(eyebrow:'Governance',title:'Approvals',subtitle:'${pending.length} requests need your decision',children:[if(pending.isEmpty)const _Panel('Queue clear','No agent actions require a decision','Governance current',statusColor:Color(0xFF087568))else...pending.map((x)=>_Panel(x.action,'Requested by agent · ${x.reason}','${x.risk} impact · ${_when(x.createdAt)}',onTap:()=>_decision(context,x))),const Text('Decision details',style:_section),const SizedBox(height:12),const _Panel('Policy check','Sensitive actions require workspace approval','Passed with approval',statusColor:Color(0xFF087568)),const _Panel('Audit trail','Request, context, policy, and decision retained','7 year retention')]);}
  Future<void> _decision(BuildContext context,WorkspaceApproval item)=>showModalBottomSheet(context:context,showDragHandle:true,builder:(context)=>SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(24,0,24,24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(item.action,style:_title),const SizedBox(height:8),Text(item.reason),const SizedBox(height:16),FilledButton(onPressed:(){Navigator.pop(context);controller.decide(item.id,approve:true);},child:const Text('Approve')),OutlinedButton(onPressed:(){Navigator.pop(context);controller.decide(item.id,approve:false);},child:const Text('Reject'))]))));}

class FigmaAutomationsScreen extends StatelessWidget {const FigmaAutomationsScreen({super.key,required this.controller});final WorkspaceController controller;@override Widget build(BuildContext context){final schedules=controller.schedules;final runs=controller.automations;return _OpsPage(eyebrow:'Durable runs',title:'Automations',subtitle:'Schedules continue after the app closes.',children:[if(schedules.isEmpty)const _Panel('No schedules','Create a schedule from an automation workflow','Not scheduled')else...schedules.map((x)=>_Panel(x.name,'${x.cron} · ${x.timezone}',x.enabled?'Active':'Paused',statusColor:x.enabled?const Color(0xFF087568):const Color(0xFF667980),onTap:()=>_schedule(context,x))),const Text('Recent runs',style:_section),const SizedBox(height:12),if(runs.isEmpty)const _Panel('No recent runs','Automation history will appear here','No activity')else...runs.map((x)=>_Panel(x.name,'${x.currentStep}/${x.stepCount} steps · ${_when(x.updatedAt)}',x.status,statusColor:x.status=='completed'?const Color(0xFF087568):x.status=='failed'?const Color(0xFFA73730):const Color(0xFF667980),onTap:()=>_run(context,x)))]);}
  Future<void> _run(BuildContext context,WorkspaceAutomation run)=>showModalBottomSheet(context:context,showDragHandle:true,builder:(context)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:Text(run.name),subtitle:Text(run.status)),if(run.status!='completed')ListTile(leading:const Icon(Icons.stop),title:const Text('Cancel run'),onTap:(){Navigator.pop(context);controller.transitionAutomation(run.id,'cancel');}),if(run.status=='failed'||run.status=='cancelled')ListTile(leading:const Icon(Icons.refresh),title:const Text('Retry run'),onTap:(){Navigator.pop(context);controller.transitionAutomation(run.id,'retry');})])));
  Future<void> _schedule(BuildContext context,AutomationSchedule value)=>showModalBottomSheet(context:context,showDragHandle:true,builder:(context)=>SafeArea(child:ListTile(leading:Icon(value.enabled?Icons.pause:Icons.play_arrow),title:Text(value.enabled?'Disable schedule':'Enable schedule'),onTap:()=>Navigator.pop(context))));}

class FigmaFilesMemoryScreen extends StatelessWidget {const FigmaFilesMemoryScreen({super.key,required this.controller});final WorkspaceController controller;@override Widget build(BuildContext context)=>_OpsPage(eyebrow:'Knowledge',title:'Files & memory',subtitle:'Search workspace files and saved agent memory',children:[if(controller.files.isEmpty)const _Panel('No workspace files','Upload files from the detailed resource view','Empty')else...controller.files.take(3).map((x)=>_Panel(x.name,'${x.contentType} · ${_bytes(x.sizeBytes)}','Available to governed agents',onTap:()=>_file(context,x))),const Text('Saved memory',style:_section),const SizedBox(height:12),if(controller.memories.isEmpty)const _Panel('No saved memory','Agent memory will appear after tasks retain context','Empty')else...controller.memories.take(3).map((x)=>_Panel(x.content,x.sourceType,'Shared memory',onTap:()=>_memory(context,x)))]);
  Future<void> _file(BuildContext context,WorkspaceFile file)=>showModalBottomSheet(context:context,showDragHandle:true,builder:(context)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:Text(file.name),subtitle:Text(file.contentType)),ListTile(leading:const Icon(Icons.download),title:const Text('Download'),onTap:(){Navigator.pop(context);controller.repository.downloadFile(file);}),ListTile(leading:const Icon(Icons.delete_outline),title:const Text('Delete'),onTap:(){Navigator.pop(context);controller.deleteFile(file.id);})])));
  Future<void> _memory(BuildContext context,WorkspaceMemory memory)=>showModalBottomSheet(context:context,showDragHandle:true,builder:(context)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:Text(memory.content),subtitle:Text(memory.sourceType)),ListTile(leading:const Icon(Icons.delete_outline),title:const Text('Delete memory'),onTap:(){Navigator.pop(context);controller.deleteMemory(memory.id);})])));
}

String _when(DateTime value){final d=DateTime.now().difference(value);return d.inMinutes<1?'now':d.inHours<1?'${d.inMinutes} min ago':d.inDays<1?'${d.inHours}h ago':'${d.inDays}d ago';}String _bytes(int value)=>value<1024?'$value B':value<1048576?'${(value/1024).toStringAsFixed(1)} KB':'${(value/1048576).toStringAsFixed(1)} MB';
const _small=TextStyle(fontSize:12,color:Color(0xFF667980));const _eyebrow=TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:Color(0xFF087568));const _title=TextStyle(fontSize:26,fontWeight:FontWeight.w700,color:Color(0xFF172026));const _section=TextStyle(fontSize:16,fontWeight:FontWeight.w600,color:Color(0xFF172026));
