import 'package:flutter/material.dart';
import 'workspace_controller.dart';
import 'workspace_models.dart';
import 'workspace_screens.dart';

class FigmaTasksScreen extends StatefulWidget {const FigmaTasksScreen({super.key,required this.controller});final WorkspaceController controller;@override State<FigmaTasksScreen> createState()=>_FigmaTasksScreenState();}
class _FigmaTasksScreenState extends State<FigmaTasksScreen>{String filter='All';@override Widget build(BuildContext context){final tasks=widget.controller.tasks.where((x)=>filter=='All'||filter=='Running'&&x.status==WorkStatus.running||filter=='Needs input'&&x.status==WorkStatus.waitingApproval||filter=='Done'&&x.status==WorkStatus.completed).toList();return ColoredBox(color:const Color(0xFFF3F5F6),child:RefreshIndicator(onRefresh:widget.controller.load,child:ListView(padding:const EdgeInsets.fromLTRB(24,18,24,28),children:[const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('9:41',style:_small),Text('5G  100%',style:_small)]),const SizedBox(height:12),const Text('WORK QUEUE',style:_eyebrow),const SizedBox(height:12),const Text('Tasks',style:_title),const SizedBox(height:8),Wrap(spacing:4,children:['All','Running','Needs input','Done'].map((x)=>ChoiceChip(label:Text(x),selected:filter==x,onSelected:(_)=>setState(()=>filter=x),showCheckmark:false,side:BorderSide.none,backgroundColor:Colors.transparent,selectedColor:Colors.white)).toList()),const SizedBox(height:8),if(tasks.isEmpty)_empty()else...tasks.expand((task)=>[_task(context,task),const SizedBox(height:12)]),OutlinedButton.icon(onPressed:()=>_create(context),icon:const Icon(Icons.add),label:const Text('Create task'))])));}
  Widget _task(BuildContext context,WorkspaceTask task)=>InkWell(onTap:()async{final live=await widget.controller.loadTask(task.id);if(context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>TaskDetailScreen(controller:widget.controller,task:live)));},borderRadius:BorderRadius.circular(8),child:Container(constraints:const BoxConstraints(minHeight:86),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,border:Border.all(color:const Color(0xFFD8E0E3)),borderRadius:BorderRadius.circular(8)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(task.title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w600,color:Color(0xFF172026))),const SizedBox(height:6),Text(task.prompt,maxLines:1,overflow:TextOverflow.ellipsis,style:_small),const SizedBox(height:6),Text(_status(task),style:TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:_color(task.status)))])));
  Future<void> _create(BuildContext context)async{final c=TextEditingController();final value=await showModalBottomSheet<String>(context:context,isScrollControlled:true,showDragHandle:true,builder:(context)=>Padding(padding:EdgeInsets.fromLTRB(24,8,24,MediaQuery.viewInsetsOf(context).bottom+24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('Create task',style:_title),const SizedBox(height:16),TextField(controller:c,minLines:3,maxLines:5,decoration:const InputDecoration(labelText:'Task instructions')),const SizedBox(height:12),FilledButton(onPressed:()=>Navigator.pop(context,c.text.trim()),child:const Text('Run task'))])));c.dispose();if(value!=null&&value.isNotEmpty)await widget.controller.createTask(value);}
  static Widget _empty()=>Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:Colors.white,border:Border.all(color:const Color(0xFFD8E0E3)),borderRadius:BorderRadius.circular(8)),child:const Text('No tasks match this filter.',textAlign:TextAlign.center));
  static String _status(WorkspaceTask t)=>switch(t.status){WorkStatus.running=>'Running · ${t.run?.steps.length??0} steps',WorkStatus.waitingApproval=>'Approval required',WorkStatus.completed=>'Completed',WorkStatus.failed=>'Failed · review required',WorkStatus.cancelled=>'Cancelled',_=>'Queued'};
  static Color _color(WorkStatus s)=>s==WorkStatus.completed?const Color(0xFF087568):s==WorkStatus.failed||s==WorkStatus.cancelled?const Color(0xFFA73730):s==WorkStatus.waitingApproval?const Color(0xFF765808):const Color(0xFF667980);
  static const _small=TextStyle(fontSize:12,color:Color(0xFF667980));static const _eyebrow=TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:Color(0xFF667980));static const _title=TextStyle(fontSize:26,fontWeight:FontWeight.w700,color:Color(0xFF172026));
}
