import 'package:flutter/material.dart';
import 'workspace_controller.dart';
import 'workspace_models.dart';

class FigmaHomeScreen extends StatelessWidget {
  const FigmaHomeScreen({super.key,required this.controller});final WorkspaceController controller;
  @override Widget build(BuildContext context){final tasks=controller.tasks;final approvals=controller.pendingApprovals;final running=tasks.where((x)=>x.status==WorkStatus.running).toList();final completed=tasks.where((x)=>x.status==WorkStatus.completed).toList();final automations=controller.automations;final now=DateTime.now();return ColoredBox(color:const Color(0xFFF3F5F6),child:RefreshIndicator(onRefresh:controller.load,child:ListView(padding:const EdgeInsets.fromLTRB(24,18,24,24),children:[
    Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(TimeOfDay.fromDateTime(now).format(context),style:_small),const Text('5G  100%',style:_small)]),const SizedBox(height:12),const Text('ACME OPERATIONS',style:_eyebrow),const SizedBox(height:12),Text(_greeting(now),style:_title),const SizedBox(height:12),Text('${_date(now)} · ${running.length} agents active',style:_success),const SizedBox(height:12),
    _card(running.isEmpty?'No active agent runs':running.first.title,running.isEmpty?'Create a task to start governed work':'Agent task · updated ${_when(running.first.updatedAt)}',running.isEmpty?'Ready':'Running'),const SizedBox(height:12),
    _card(approvals.isEmpty?'No approvals waiting':approvals.first.action,approvals.isEmpty?'Governance queue is clear':'Requested by agent · ${_when(approvals.first.createdAt)}',approvals.isEmpty?'Clear':'Approval required',warning:approvals.isNotEmpty),const SizedBox(height:12),const Text('Activity',style:TextStyle(fontSize:16,fontWeight:FontWeight.w600,color:Color(0xFF172026))),const SizedBox(height:12),
    _card(completed.isEmpty?'Recent task activity':completed.first.title,completed.isEmpty?'Completed work will appear here':'Output saved · ${_when(completed.first.updatedAt)}',completed.isEmpty?'No recent output':'Completed',success:completed.isNotEmpty),const SizedBox(height:12),
    _card(automations.isEmpty?'No automation scheduled':automations.first.name,automations.isEmpty?'Create a durable schedule from Automations':'Updated ${_when(automations.first.updatedAt)}',automations.isEmpty?'Not scheduled':automations.first.status),
  ])));}
  static Widget _card(String title,String subtitle,String status,{bool warning=false,bool success=false})=>Container(minHeight:86,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,border:Border.all(color:const Color(0xFFD8E0E3)),borderRadius:BorderRadius.circular(8)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(title,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(fontSize:14,fontWeight:FontWeight.w600,color:success?const Color(0xFF087568):const Color(0xFF172026))),const SizedBox(height:6),Text(subtitle,maxLines:1,overflow:TextOverflow.ellipsis,style:_small),const SizedBox(height:6),Text(status,style:TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:warning?const Color(0xFF765808):success?const Color(0xFF087568):const Color(0xFF667980)))]));
  static String _greeting(DateTime value)=>value.hour<12?'Good morning':value.hour<18?'Good afternoon':'Good evening';
  static String _date(DateTime value)=>'${const ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][value.weekday-1]}, ${value.day} ${const ['January','February','March','April','May','June','July','August','September','October','November','December'][value.month-1]}';
  static String _when(DateTime value){final d=DateTime.now().difference(value);return d.inMinutes<1?'now':d.inHours<1?'${d.inMinutes} min ago':d.inDays<1?'${d.inHours}h ago':'${d.inDays}d ago';}
  static const _small=TextStyle(fontSize:12,color:Color(0xFF667980));static const _eyebrow=TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:Color(0xFF087568));static const _title=TextStyle(fontSize:26,fontWeight:FontWeight.w700,color:Color(0xFF172026));static const _success=TextStyle(fontSize:13,color:Color(0xFF087568));
}
