import 'package:flutter/material.dart';
import 'workspace_controller.dart';
import 'workspace_models.dart';

class TasksScreen extends StatefulWidget { const TasksScreen({super.key, required this.controller}); final WorkspaceController controller; @override State<TasksScreen> createState()=>_TasksState(); }
class _TasksState extends State<TasksScreen>{final prompt=TextEditingController();@override void dispose(){prompt.dispose();super.dispose();}@override Widget build(BuildContext context){final c=widget.controller;return RefreshIndicator(onRefresh:c.load,child:CustomScrollView(slivers:[SliverPadding(padding:const EdgeInsets.fromLTRB(16,16,16,8),sliver:SliverToBoxAdapter(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('Run an agent task',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:12),TextField(controller:prompt,minLines:3,maxLines:6,decoration:const InputDecoration(border:OutlineInputBorder(),labelText:'Task instructions',hintText:'Describe the result the agent should produce')),const SizedBox(height:10),FilledButton.icon(onPressed:c.mutating?null:()async{final value=prompt.text.trim();if(value.isEmpty)return;final task=await c.createTask(value);if(task!=null&&mounted){prompt.clear();await Navigator.push(context,MaterialPageRoute(builder:(_)=>TaskDetailScreen(controller:c,task:task)));}},icon:c.mutating?const SizedBox.square(dimension:16,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.play_arrow),label:const Text('Run task')),const SizedBox(height:18),Text('Recent tasks',style:Theme.of(context).textTheme.titleMedium)]))),if(c.tasks.isEmpty)const SliverFillRemaining(hasScrollBody:false,child:_Empty(icon:Icons.task_alt,title:'No tasks',text:'Create a task to start the agent runtime.'))else SliverList.builder(itemCount:c.tasks.length,itemBuilder:(context,i){final task=c.tasks[i];return ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:3),leading:_StatusIcon(task.status),title:Text(task.title,maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text('${_status(task.status)} · ${_when(task.updatedAt)}'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>TaskDetailScreen(controller:c,task:task))));})]));}}

class TaskDetailScreen extends StatefulWidget { const TaskDetailScreen({super.key,required this.controller,required this.task});final WorkspaceController controller;final WorkspaceTask task;@override State<TaskDetailScreen> createState()=>_TaskDetailState(); }
class _TaskDetailState extends State<TaskDetailScreen>{late WorkspaceTask task=widget.task;Future<void> action(Future<WorkspaceTask?> Function() fn)async{final next=await fn();if(next!=null&&mounted)setState(()=>task=next);}@override Widget build(BuildContext context){final run=task.run;final terminal={WorkStatus.completed,WorkStatus.failed,WorkStatus.cancelled}.contains(task.status);return Scaffold(appBar:AppBar(title:const Text('Task detail')),body:ListView(padding:const EdgeInsets.all(16),children:[Row(children:[Expanded(child:Text(task.title,style:Theme.of(context).textTheme.titleLarge)),_StatusChip(task.status)]),const SizedBox(height:8),Text(task.prompt,style:Theme.of(context).textTheme.bodyMedium),const SizedBox(height:16),Wrap(spacing:8,children:[if(!terminal)OutlinedButton.icon(onPressed:()=>action(()=>widget.controller.cancelTask(task.id)),icon:const Icon(Icons.stop),label:const Text('Cancel')),if(task.status==WorkStatus.failed||task.status==WorkStatus.cancelled)FilledButton.icon(onPressed:()=>action(()=>widget.controller.resumeTask(task.id)),icon:const Icon(Icons.refresh),label:const Text('Resume'))]),const Divider(height:32),Text('Execution trace',style:Theme.of(context).textTheme.titleMedium),if(run==null||run.steps.isEmpty)const _Empty(icon:Icons.timeline,title:'No trace available',text:'Execution steps will appear when the run begins.')else ...run.steps.asMap().entries.map((entry)=>_TimelineStep(step:entry.value,index:entry.key+1,last:entry.key==run.steps.length-1)),if(run?.result case final result?)...[const Divider(height:32),Text('Result',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:8),SelectableText(result)] ]));}}

class ApprovalsScreen extends StatelessWidget {const ApprovalsScreen({super.key,required this.controller});final WorkspaceController controller;@override Widget build(BuildContext context){final items=controller.approvals;return RefreshIndicator(onRefresh:controller.load,child:items.isEmpty?const ListView(children:[SizedBox(height:150),_Empty(icon:Icons.verified_outlined,title:'Queue clear',text:'No agent actions need approval.')]):ListView.separated(padding:const EdgeInsets.all(16),itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(context,i){final a=items[i];return Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(a.action,style:Theme.of(context).textTheme.titleMedium)),Chip(label:Text('${a.risk} risk'))]),Text(a.reason),const SizedBox(height:6),Text('${a.taskId} · ${_when(a.createdAt)}',style:Theme.of(context).textTheme.bodySmall),if(a.status=='pending')...[const SizedBox(height:12),Row(children:[Expanded(child:FilledButton.icon(onPressed:controller.mutating?null:()=>controller.decide(a.id,approve:true),icon:const Icon(Icons.check),label:const Text('Approve'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:controller.mutating?null:()=>controller.decide(a.id,approve:false),icon:const Icon(Icons.close),label:const Text('Reject')))])]else Padding(padding:const EdgeInsets.only(top:10),child:Text(a.status.toUpperCase(),style:Theme.of(context).textTheme.labelMedium))]))); }));}}

class AutomationsScreen extends StatelessWidget {const AutomationsScreen({super.key,required this.controller});final WorkspaceController controller;@override Widget build(BuildContext context){final items=controller.automations;return RefreshIndicator(onRefresh:controller.load,child:items.isEmpty?const ListView(children:[SizedBox(height:150),_Empty(icon:Icons.account_tree_outlined,title:'No automations',text:'Create workflows in the workbench to run them here.')]):ListView.builder(padding:const EdgeInsets.all(16),itemCount:items.length,itemBuilder:(context,i){final a=items[i];return Card(child:ListTile(isThreeLine:true,leading:const Icon(Icons.account_tree),title:Text(a.name),subtitle:Text('${a.status} · ${a.currentStep}/${a.stepCount} steps\nUpdated ${_when(a.updatedAt)}'),trailing:PopupMenuButton<String>(onSelected:(value)=>value=='start'?controller.startAutomation(a.id):controller.transitionAutomation(a.id,value),itemBuilder:(_)=>[const PopupMenuItem(value:'start',child:Text('Run now')),if(a.status=='paused')const PopupMenuItem(value:'resume',child:Text('Resume')),if(a.status=='failed'||a.status=='cancelled')const PopupMenuItem(value:'retry',child:Text('Retry')),if(a.status!='completed'&&a.status!='cancelled')const PopupMenuItem(value:'cancel',child:Text('Cancel'))]))); }));}}

class WorkspaceResourcesScreen extends StatefulWidget {const WorkspaceResourcesScreen({super.key,required this.controller});final WorkspaceController controller;@override State<WorkspaceResourcesScreen> createState()=>_ResourcesState();}
class _ResourcesState extends State<WorkspaceResourcesScreen> with SingleTickerProviderStateMixin{late final tabs=TabController(length:2,vsync:this);final memory=TextEditingController(),task=TextEditingController(),path=TextEditingController();@override void dispose(){tabs.dispose();memory.dispose();task.dispose();path.dispose();super.dispose();}@override Widget build(BuildContext context){final c=widget.controller;return Column(children:[TabBar(controller:tabs,tabs:const [Tab(text:'Files'),Tab(text:'Memory')]),Expanded(child:TabBarView(controller:tabs,children:[_files(c),_memory(c)]))]);}Widget _files(WorkspaceController c)=>ListView(padding:const EdgeInsets.all(16),children:[Row(children:[Expanded(child:TextField(controller:path,decoration:const InputDecoration(border:OutlineInputBorder(),labelText:'Local file path'))),const SizedBox(width:8),IconButton.filled(tooltip:'Upload',onPressed:c.mutating?null:(){if(path.text.trim().isNotEmpty)c.uploadFile(path.text.trim());},icon:const Icon(Icons.upload))]),const SizedBox(height:16),if(c.files.isEmpty)const _Empty(icon:Icons.folder_open,title:'No files',text:'Upload a file to this workspace.')else ...c.files.map((f)=>ListTile(leading:const Icon(Icons.insert_drive_file_outlined),title:Text(f.name),subtitle:Text('${_bytes(f.sizeBytes)} · ${f.contentType}'),trailing:PopupMenuButton<String>(onSelected:(v)=>v=='download'?c.repository.downloadFile(f):c.deleteFile(f.id),itemBuilder:(_)=>const [PopupMenuItem(value:'download',child:Text('Download')),PopupMenuItem(value:'delete',child:Text('Delete'))])))]);Widget _memory(WorkspaceController c)=>ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:task,decoration:const InputDecoration(border:OutlineInputBorder(),labelText:'Task ID')),const SizedBox(height:8),TextField(controller:memory,minLines:2,maxLines:4,decoration:const InputDecoration(border:OutlineInputBorder(),labelText:'Memory')),const SizedBox(height:8),FilledButton.icon(onPressed:c.mutating?null:(){if(task.text.trim().isNotEmpty&&memory.text.trim().isNotEmpty){c.addMemory(task.text.trim(),memory.text.trim());memory.clear();}},icon:const Icon(Icons.add),label:const Text('Add memory')),const SizedBox(height:16),if(c.memories.isEmpty)const _Empty(icon:Icons.psychology_outlined,title:'No memories',text:'Add durable task context.')else ...c.memories.map((m)=>ListTile(leading:const Icon(Icons.psychology_outlined),title:Text(m.content,maxLines:2,overflow:TextOverflow.ellipsis),subtitle:Text('${m.sourceType} · ${m.taskId}'),trailing:IconButton(tooltip:'Delete',icon:const Icon(Icons.delete_outline),onPressed:()=>c.deleteMemory(m.id))))]);}

class _TimelineStep extends StatelessWidget{const _TimelineStep({required this.step,required this.index,required this.last});final RunStep step;final int index;final bool last;@override Widget build(BuildContext context)=>IntrinsicHeight(child:Row(crossAxisAlignment:CrossAxisAlignment.stretch,children:[SizedBox(width:32,child:Column(children:[CircleAvatar(radius:12,child:Text('$index',style:const TextStyle(fontSize:11))),if(!last)Expanded(child:Container(width:1,color:Theme.of(context).dividerColor))])),const SizedBox(width:10),Expanded(child:Padding(padding:const EdgeInsets.only(bottom:20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(step.type.replaceAll('_',' '),style:Theme.of(context).textTheme.labelLarge),Text(step.summary),Text(_when(step.createdAt),style:Theme.of(context).textTheme.bodySmall)]))) ]));}
class _StatusIcon extends StatelessWidget{const _StatusIcon(this.value);final WorkStatus value;@override Widget build(BuildContext context)=>CircleAvatar(backgroundColor:_color(context,value).withValues(alpha:.14),child:Icon(value==WorkStatus.completed?Icons.check:value==WorkStatus.failed?Icons.error_outline:value==WorkStatus.cancelled?Icons.stop:Icons.schedule,color:_color(context,value)));}
class _StatusChip extends StatelessWidget{const _StatusChip(this.value);final WorkStatus value;@override Widget build(BuildContext context)=>Chip(label:Text(_status(value)),backgroundColor:_color(context,value).withValues(alpha:.14));}
class _Empty extends StatelessWidget{const _Empty({required this.icon,required this.title,required this.text});final IconData icon;final String title,text;@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.symmetric(horizontal:24,vertical:44),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:38,color:Theme.of(context).colorScheme.primary),const SizedBox(height:12),Text(title,style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:4),Text(text,textAlign:TextAlign.center,style:Theme.of(context).textTheme.bodySmall)]));}
Color _color(BuildContext c,WorkStatus s)=>s==WorkStatus.completed?Colors.green:s==WorkStatus.failed||s==WorkStatus.cancelled?Theme.of(c).colorScheme.error:Colors.amber.shade800;
String _status(WorkStatus value)=>value.name.replaceAllMapped(RegExp(r'([A-Z])'),(m)=>' ${m.group(1)!.toLowerCase()}');
String _when(DateTime value){final d=DateTime.now().difference(value);if(d.inMinutes<1)return 'now';if(d.inHours<1)return '${d.inMinutes}m ago';if(d.inDays<1)return '${d.inHours}h ago';return '${d.inDays}d ago';}
String _bytes(int value)=>value<1024?'$value B':value<1048576?'${(value/1024).toStringAsFixed(1)} KB':'${(value/1048576).toStringAsFixed(1)} MB';
