import 'package:flutter/material.dart';

import 'auth_controller.dart';
import 'auth_repository.dart';

class FigmaAccountPage extends StatelessWidget {
  const FigmaAccountPage({super.key,required this.eyebrow,required this.title,required this.subtitle,required this.children});
  final String eyebrow,title,subtitle;final List<Widget> children;
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF3F5F6),body:SafeArea(child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:393),child:ListView(padding:const EdgeInsets.fromLTRB(24,20,24,28),children:[
    const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('9:41',style:TextStyle(fontSize:12,fontWeight:FontWeight.w600,color:Color(0xFF667980))),Text('5G  100%',style:TextStyle(fontSize:12,fontWeight:FontWeight.w600,color:Color(0xFF667980)))]),
    const SizedBox(height:14),Text(eyebrow.toUpperCase(),style:const TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:Color(0xFF087568))),const SizedBox(height:14),Text(title,style:const TextStyle(fontSize:26,fontWeight:FontWeight.w700,color:Color(0xFF172026))),const SizedBox(height:14),Text(subtitle,style:const TextStyle(fontSize:13,color:Color(0xFF667980))),const SizedBox(height:14),..._spaced(children),
  ])))));
  static List<Widget> _spaced(List<Widget> values)=>[for(var i=0;i<values.length;i++)...[values[i],if(i<values.length-1)const SizedBox(height:14)]];
}

class FigmaPanel extends StatelessWidget {
  const FigmaPanel({super.key,required this.title,required this.subtitle,this.selected=false,this.onTap});
  final String title,subtitle;final bool selected;final VoidCallback? onTap;
  @override Widget build(BuildContext context)=>Material(color:Colors.white,borderRadius:BorderRadius.circular(8),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(8),child:Container(constraints:const BoxConstraints(minHeight:72),padding:const EdgeInsets.all(14),decoration:BoxDecoration(border:Border.all(color:selected?const Color(0xFF087568):const Color(0xFFD8E0E3)),borderRadius:BorderRadius.circular(8)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(title,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w600,color:Color(0xFF172026))),const SizedBox(height:6),Text(subtitle,style:const TextStyle(fontSize:12,color:Color(0xFF667980)))]))));
}

ButtonStyle get figmaPrimary=>FilledButton.styleFrom(minimumSize:const Size.fromHeight(48),backgroundColor:const Color(0xFF087568),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(8)));
ButtonStyle get figmaSecondary=>OutlinedButton.styleFrom(minimumSize:const Size.fromHeight(48),foregroundColor:const Color(0xFF172026),side:const BorderSide(color:Color(0xFFD8E0E3)),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(8)));

class OtpVerificationScreen extends StatefulWidget {
  const OtpVerificationScreen({super.key,required this.controller,required this.challengeId});final AuthController controller;final String challengeId;
  @override State<OtpVerificationScreen> createState()=>_OtpVerificationScreenState();
}
class _OtpVerificationScreenState extends State<OtpVerificationScreen>{final code=TextEditingController();bool busy=false;@override void dispose(){code.dispose();super.dispose();}@override Widget build(BuildContext context)=>FigmaAccountPage(eyebrow:'Security check',title:'Enter verification code',subtitle:'We sent a six-digit code to your configured work account.',children:[TextField(controller:code,maxLength:6,keyboardType:TextInputType.number,textAlign:TextAlign.center,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w600,letterSpacing:12),decoration:const InputDecoration(counterText:'',helperText:'Code expires in 10:00',filled:true,fillColor:Colors.white)),FilledButton(style:figmaPrimary,onPressed:busy?null:_verify,child:Text(busy?'Verifying...':'Verify')),OutlinedButton(style:figmaSecondary,onPressed:busy?null:()=>Navigator.pop(context),child:const Text('Send another code')),const FigmaPanel(title:'Use another method',subtitle:'Password · Recovery code')]);Future<void> _verify()async{setState(()=>busy=true);await widget.controller.completeExternalSignIn(()=>widget.controller.repository.verifyOtp(challengeId:widget.challengeId,code:code.text.trim()));if(mounted)Navigator.pop(context);}}

class PasswordRecoveryScreen extends StatefulWidget {const PasswordRecoveryScreen({super.key,required this.controller,required this.tenantId,required this.workspaceId,required this.userId});final AuthController controller;final String tenantId,workspaceId,userId;@override State<PasswordRecoveryScreen> createState()=>_PasswordRecoveryScreenState();}
class _PasswordRecoveryScreenState extends State<PasswordRecoveryScreen>{bool busy=false;@override Widget build(BuildContext context)=>FigmaAccountPage(eyebrow:'Account recovery',title:'Reset your password',subtitle:'Send a recovery challenge for the work account associated with ANUM.',children:[FigmaPanel(title:'Work account',subtitle:widget.userId),FilledButton(style:figmaPrimary,onPressed:busy?null:_send,child:Text(busy?'Sending...':'Send recovery link')),OutlinedButton(style:figmaSecondary,onPressed:()=>Navigator.pop(context),child:const Text('Back to sign in')),const FigmaPanel(title:'Enterprise account',subtitle:'Contact your organization administrator if sign-in is managed by SSO.')]);Future<void> _send()async{setState(()=>busy=true);final challenge=await widget.controller.repository.requestPasswordReset(tenantId:widget.tenantId,workspaceId:widget.workspaceId,userId:widget.userId);if(!mounted)return;final token=await _entry(context,'Reset token');if(token==null||!mounted)return;final password=await _entry(context,'New password',obscure:true);if(password!=null)await widget.controller.completeExternalSignIn(()=>widget.controller.repository.resetPassword(challengeId:challenge,token:token,newPassword:password));if(mounted)Navigator.pop(context);}}

Future<String?> _entry(BuildContext context,String label,{bool obscure=false})async{final c=TextEditingController();final result=await showModalBottomSheet<String>(context:context,isScrollControlled:true,builder:(context)=>Padding(padding:EdgeInsets.fromLTRB(24,24,24,MediaQuery.viewInsetsOf(context).bottom+24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(label,style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:16),TextField(controller:c,autofocus:true,obscureText:obscure,decoration:InputDecoration(labelText:label)),const SizedBox(height:16),FilledButton(style:figmaPrimary,onPressed:()=>Navigator.pop(context,c.text.trim()),child:const Text('Continue'))]));c.dispose();return result==null||result.isEmpty?null:result;}

class WorkspaceSwitcherScreen extends StatelessWidget {const WorkspaceSwitcherScreen({super.key,required this.repository});final AuthRepository repository;@override Widget build(BuildContext context)=>FigmaAccountPage(eyebrow:'Workspace',title:'Switch workspace',subtitle:'Your roles and agent access change with the selected workspace.',children:[FigmaPanel(title:'Acme Operations',subtitle:'Owner · 3 agents active',selected:true,onTap:()=>repository.switchWorkspace('default')),FigmaPanel(title:'Acme Product',subtitle:'Member · 1 approval waiting',onTap:()=>repository.switchWorkspace('product')),FigmaPanel(title:'Personal',subtitle:'Private · 2 scheduled tasks',onTap:()=>repository.switchWorkspace('personal')),FilledButton(style:figmaPrimary,onPressed:()=>Navigator.pop(context),child:const Text('Create workspace')),OutlinedButton(style:figmaSecondary,onPressed:()=>Navigator.pop(context),child:const Text('Manage memberships'))]);}
