import { useCallback, useEffect, useState } from 'react';
import { Clock3, Pause, Play, Plus, RefreshCw, RotateCcw, Square, Workflow } from 'lucide-react';
import { createAutomationWorkflow, getAutomationRuns, getAutomationWorkflows, startAutomationRun, transitionAutomationRun, type AutomationRun, type AutomationWorkflow } from './lib/api';

export function AutomationWorkbench() {
  const [workflows, setWorkflows] = useState<AutomationWorkflow[]>([]);
  const [runs, setRuns] = useState<AutomationRun[]>([]);
  const [name, setName] = useState('Daily operations review');
  const [action, setAction] = useState('task.execute');
  const [selected, setSelected] = useState('');
  const [message, setMessage] = useState('Loading durable automation state...');
  const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { try { const [workflowItems, runItems] = await Promise.all([getAutomationWorkflows(), getAutomationRuns()]); setWorkflows(workflowItems); setRuns(runItems); setSelected((current) => current || workflowItems[0]?.id || ''); setMessage(`${workflowItems.length} workflows and ${runItems.length} runs loaded.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load automation state.'); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  async function perform(operation: () => Promise<unknown>, success: string) { setBusy(true); try { await operation(); await refresh(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : 'Automation operation failed.'); } finally { setBusy(false); } }
  return <>
    <section className="moduleIntro"><div><p className="eyebrow">Durable execution</p><h2>Automation workbench</h2><p>Launch, inspect, pause, resume, and retry replay-safe agent workflows.</p></div><button type="button" onClick={() => void refresh()}><RefreshCw size={17} />Refresh</button></section>
    <section className="automationGrid">
      <section className="surface automationComposer"><div className="sectionHeader"><div><p className="eyebrow">Workflow definition</p><h2>Create automation</h2></div><Workflow size={20} /></div><label className="field"><span>Name</span><input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>First action</span><select value={action} onChange={(event) => setAction(event.target.value)}><option value="task.execute">Execute agent task</option><option value="pause">Wait for external signal</option><option value="notify">Send notification</option></select></label><div className="actions"><button type="button" disabled={busy || !name.trim()} onClick={() => void perform(async () => { const item = await createAutomationWorkflow(name, action); setSelected(item.id); }, 'Workflow saved durably.')}><Plus size={17} />Create</button></div></section>
      <section className="surface automationComposer"><div className="sectionHeader"><div><p className="eyebrow">Replay-safe launch</p><h2>Start workflow</h2></div><Play size={20} /></div><label className="field"><span>Workflow</span><select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Select a workflow</option>{workflows.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="actions"><button type="button" disabled={busy || !selected} onClick={() => void perform(() => startAutomationRun(selected, crypto.randomUUID()), 'Workflow run started.')}><Play size={17} />Run now</button></div><p className="notice" role="status"><Clock3 size={14} />{message}</p></section>
    </section>
    <section className="surface runTable"><div className="sectionHeader"><div><p className="eyebrow">Execution history</p><h2>Workflow runs</h2></div><span className="muted">{runs.length} total</span></div>{runs.length === 0 ? <div className="emptyState"><Workflow /><h3>No workflow runs</h3><p>Create and launch an automation to begin.</p></div> : runs.map((run) => <article className="runRow" key={run.id}><div><strong>{workflows.find((item) => item.id === run.workflow_id)?.name ?? run.workflow_id}</strong><code>{run.id}</code></div><span className={`statusBadge ${run.status === 'completed' ? 'success' : run.status === 'failed' || run.status === 'cancelled' ? 'dangerTone' : 'warning'}`}>{run.status}</span><span>{run.current_step} / {run.steps.length} steps</span><div className="runActions">{run.status === 'paused' && <button title="Resume" aria-label="Resume run" disabled={busy} onClick={() => void perform(() => transitionAutomationRun(run.id, 'resume'), 'Run resumed.')}><Play size={16} /></button>}{['failed', 'cancelled'].includes(run.status) && <button title="Retry" aria-label="Retry run" disabled={busy} onClick={() => void perform(() => transitionAutomationRun(run.id, 'retry'), 'Retry started.')}><RotateCcw size={16} /></button>}{!['completed', 'cancelled'].includes(run.status) && <button title="Cancel" aria-label="Cancel run" disabled={busy} onClick={() => void perform(() => transitionAutomationRun(run.id, 'cancel'), 'Run cancelled.')}><Square size={16} /></button>}{run.status === 'paused' && <Pause size={16} aria-label="Paused" />}</div></article>)}</section>
  </>;
}
