#!/usr/bin/env python3
"""Turn one version of a CustomResourceDefinition into a kubeconform JSON schema.

Usage: crd-schema.py <crd.yaml|crd.json> <version> > schema.json

kubeconform has no schemas for custom resources, so infra/helm/ci/lint.sh validates the
admission policies (policy.sigstore.dev ClusterImagePolicy) against a schema generated by
this script from the CRD of the pinned policy-controller chart and committed under
infra/helm/ci/schemas/. infra/helm/ci/kind-smoke.sh regenerates it from the CRD that the
digest-pinned chart installed (`kubectl get crd -o json`) and fails if it differs, so
the committed schema cannot drift from the controller CI installs.

Like kubeconform's openapi2jsonschema, every object with declared properties gets
`additionalProperties: false` unless it is marked x-kubernetes-preserve-unknown-fields,
so `kubeconform -strict` rejects misspelled fields. Descriptions are dropped. The output
is sorted and stable.
"""
import json
import re
import sys


def load(path):
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    try:
        return json.loads(text)
    except ValueError:
        pass
    # The chart's CRD is a Helm template: drop the {{ ... }} expressions before parsing.
    import yaml  # only needed for the YAML form (local regeneration)

    return yaml.safe_load(re.sub(r"\{\{[^}]*\}\}", "templated", text))


def strict(node):
    if isinstance(node, list):
        return [strict(item) for item in node]
    if not isinstance(node, dict):
        return node
    out = {key: strict(value) for key, value in node.items() if key not in ("description", "properties")}
    if "properties" in node:
        # A field map: keep every field name (even one called "description").
        out["properties"] = {field: strict(schema) for field, schema in node["properties"].items()}
    if "properties" in out and not out.get("x-kubernetes-preserve-unknown-fields"):
        out.setdefault("additionalProperties", False)
    return out


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: crd-schema.py <crd.yaml|crd.json> <version>")
    crd = load(sys.argv[1])
    versions = [v for v in crd["spec"]["versions"] if v["name"] == sys.argv[2]]
    if not versions:
        sys.exit(f"version {sys.argv[2]} not found in {crd['metadata']['name']}")
    schema = strict(versions[0]["schema"]["openAPIV3Schema"])
    group, kind = crd["spec"]["group"], crd["spec"]["names"]["kind"]
    properties = schema.setdefault("properties", {})
    properties["apiVersion"] = {"type": "string", "enum": [f"{group}/{sys.argv[2]}"]}
    properties["kind"] = {"type": "string", "enum": [kind]}
    properties["metadata"] = {"type": "object"}
    schema["required"] = sorted(set(schema.get("required", [])) | {"apiVersion", "kind", "metadata"})
    schema["additionalProperties"] = False
    json.dump(schema, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
