import 'package:flutter/material.dart';
import 'governance_controller.dart';
import 'governance_models.dart';

class _GovernedPage extends StatelessWidget {const _GovernedPage({required this.eyebrow,required this.title,required this.subtitle,required this.children});final String eyebrow,title,subtitle;final List<Widget> children;@override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF3F5F6),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(24,20,24,28),children:[const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('9:41',style:_small),Text('5G  100%',style:_small)]),const SizedBox(height:12),Text(eyebrow.toUpperCase(),style:_eyebrow),const SizedBox(height:12),Text(title,style:_title),const SizedBox(height:12),Text(subtitle,style:const TextStyle(fontSize:13,color:Color(0xFF667980))),const SizedBox(height:12),...children])));}
class _Item extends StatelessWidget {const _Item(this.title,this.subtitle,{this.active=false,this.onTap});final String title,subtitle;final bool active;final VoidCallback? onTap;@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Material(color:Colors.white,borderRadius:BorderRadius.circular(8),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(8),child:Container(constraints:BoxConstraints(minHeight:active?86:74),padding:const EdgeInsets.all(14),decoration:BoxDecoration(border:Border.all(color:active?const Color(0xFF087568):const Color(0xFFD8E0E3)),borderRadius:BorderRadius.circular(8)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(title,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w600,color:Color(0xFF172026))),const SizedBox(height:6),Text(subtitle,style:_small)])))));}

abstract class _GovernanceState<T extends StatefulWidget> extends State<T>{GovernanceController get controller;@override void initState(){super.initState();if(controller.snapshot==null)controller.load();}}

class FigmaPolicyPacksScreen extends StatefulWidget {const FigmaPolicyPacksScreen({super.key,required this.controller});final GovernanceController controller;@override State<FigmaPolicyPacksScreen> createState()=>_PolicyState();}
class _PolicyState extends _GovernanceState<FigmaPolicyPacksScreen>{@override GovernanceController get controller=>widget.controller;@override Widget build(BuildContext context)=>ListenableBuilder(listenable:controller,builder:(context,_){final policies=controller.snapshot?.policies??const<PolicyPack>[];return _GovernedPage(eyebrow:'Organization policy',title:'Policy packs',subtitle:'Versioned rules control tools, data, approval, memory, and models.',children:[if(policies.isEmpty)const _Item('No policy packs','Create a versioned organization policy')else...policies.map((x)=>_Item(x.name,'${x.active?'Active':'Draft'} v${x.version} · ${x.rules.length} rules',active:x.active,onTap:()=>controller.setPolicyActive(x.id,active:!x.active))),FilledButton(style:_primary,onPressed:controller.mutating?null:()=>controller.baseline('Organization baseline'),child:const Text('Create policy pack')),const SizedBox(height:12),OutlinedButton(style:_secondary,onPressed:()=>Navigator.pop(context),child:const Text('Compare versions'))]);});}

class FigmaMarketplaceScreen extends StatefulWidget {const FigmaMarketplaceScreen({super.key,required this.controller});final GovernanceController controller;@override State<FigmaMarketplaceScreen> createState()=>_MarketplaceState();}
class _MarketplaceState extends _GovernanceState<FigmaMarketplaceScreen>{@override GovernanceController get controller=>widget.controller;@override Widget build(BuildContext context)=>ListenableBuilder(listenable:controller,builder:(context,_){final items=controller.snapshot?.marketplace??const<MarketplaceItem>[];return _GovernedPage(eyebrow:'Capability marketplace',title:'Marketplace',subtitle:'Install reviewed skills and integration packs into this workspace.',children:[if(items.isEmpty)const _Item('Marketplace unavailable','No reviewed packages are available')else...items.map((x)=>_Item(x.name,'${x.verified?'Verified':x.publisher} · ${x.kind} · v${x.version}',active:x.installed,onTap:()=>x.installed?controller.uninstall(x.id):controller.install(x.id))),OutlinedButton(style:_secondary,onPressed:()=>Navigator.pop(context),child:const Text('View categories'))]);});}

class FigmaRoutingScreen extends StatefulWidget {const FigmaRoutingScreen({super.key,required this.controller});final GovernanceController controller;@override State<FigmaRoutingScreen> createState()=>_RoutingState();}
class _RoutingState extends _GovernanceState<FigmaRoutingScreen>{@override GovernanceController get controller=>widget.controller;@override Widget build(BuildContext context)=>ListenableBuilder(listenable:controller,builder:(context,_){final items=controller.snapshot?.targets??const<RoutingTarget>[];return _GovernedPage(eyebrow:'Model control',title:'Advanced routing',subtitle:'Route by risk, latency, cost, region, capability, and availability.',children:[if(items.isEmpty)const _Item('No routing targets','Configure a provider target first')else...items.map((x)=>_Item('${x.provider} · ${x.model}','${x.region} · ${x.latencyMs} ms · ${x.status}',active:x.status=='healthy',onTap:()=>_edit(context,x))),FilledButton(style:_primary,onPressed:items.isEmpty?null:()=>_edit(context,items.first),child:const Text('Edit routing rules')),const SizedBox(height:12),OutlinedButton(style:_secondary,onPressed:()=>Navigator.pop(context),child:const Text('Simulate request'))]);});Future<void> _edit(BuildContext context,RoutingTarget target)=>showModalBottomSheet(context:context,showDragHandle:true,builder:(context)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:['healthy','degraded','disabled'].map((status)=>ListTile(title:Text(status),onTap:(){Navigator.pop(context);controller.updateTarget(RoutingTarget(id:target.id,region:target.region,provider:target.provider,model:target.model,status:status,latencyMs:target.latencyMs,cost:target.cost,modalities:target.modalities,sensitivity:target.sensitivity));})).toList())));}

final _primary=FilledButton.styleFrom(minimumSize:const Size.fromHeight(48),backgroundColor:const Color(0xFF087568),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(8)));final _secondary=OutlinedButton.styleFrom(minimumSize:const Size.fromHeight(48),foregroundColor:const Color(0xFF172026),side:const BorderSide(color:Color(0xFFD8E0E3)),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(8)));const _small=TextStyle(fontSize:12,color:Color(0xFF667980));const _eyebrow=TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:Color(0xFF087568));const _title=TextStyle(fontSize:25,fontWeight:FontWeight.w700,color:Color(0xFF172026));
