import 'package:flutter/material.dart';import 'governance_controller.dart';import 'governance_models.dart';
class GovernanceScreen extends StatefulWidget {const GovernanceScreen({super.key,required this.controller});final GovernanceController controller;@override State<GovernanceScreen> createState()=>_GovernanceState();}
class _GovernanceState extends State<GovernanceScreen> with SingleTickerProviderStateMixin {
  late final tabs = TabController(length: 3, vsync: this);
  PolicyPack? selectedPolicy;
  @override void initState(){super.initState();if(widget.controller.phase==GovernancePhase.initial)widget.controller.load();}
  @override void dispose(){tabs.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>ListenableBuilder(listenable:widget.controller,builder:(context,_){final c=widget.controller,s=c.snapshot;return Scaffold(appBar:AppBar(title:const Text('Organization operations'),actions:[PopupMenuButton<String>(tooltip:'Export audit',onSelected:c.exportAudit,itemBuilder:(_)=>const[PopupMenuItem(value:'json',child:Text('Export audit JSON')),PopupMenuItem(value:'csv',child:Text('Export audit CSV'))]),IconButton(tooltip:'Refresh',onPressed:c.mutating?null:c.load,icon:const Icon(Icons.refresh))]),body:Column(children:[if(c.phase==GovernancePhase.offline)_Banner(c.message??'Governance services are offline.'),if(c.phase==GovernancePhase.error)_Banner(c.message??'Unable to load governance.'),TabBar(controller:tabs,tabs:const[Tab(text:'Governance'),Tab(text:'Marketplace'),Tab(text:'Routing')]),Expanded(child:s==null&&c.phase==GovernancePhase.loading?const Center(child:CircularProgressIndicator()):s==null?const _Empty('No governance data'):TabBarView(controller:tabs,children:[_policies(c,s),_market(c,s),_routing(c,s)]))]));});

  Widget _policies(GovernanceController c,GovernanceSnapshot s)=>LayoutBuilder(builder:(context,constraints){
    final list=ListView(padding:const EdgeInsets.all(16),children:[_metrics([('Policy packs','${s.summary.policyPacks}'),('Active','${s.summary.activePolicyPacks}'),('Roles','${s.summary.roleTemplates}'),('Approval rules','${s.summary.approvalRules}')]),const SizedBox(height:16),FilledButton.icon(onPressed:c.mutating?null:()=>c.baseline('Organization baseline'),icon:const Icon(Icons.add),label:const Text('Add baseline policy')),const SizedBox(height:12),if(s.policies.isEmpty)const _Empty('No policy packs')else...s.policies.map((x)=>Card(child:ListTile(selected:selectedPolicy?.id==x.id,onTap:()=>setState(()=>selectedPolicy=x),leading:Icon(x.active?Icons.verified_user:Icons.policy_outlined),title:Text(x.name),subtitle:Text('Version ${x.version}'),trailing:Chip(label:Text(x.active?'Active':'Archived')))))]);
    if(constraints.maxWidth<840)return list;
    final policy=selectedPolicy??(s.policies.isEmpty?null:s.policies.first);
    return Row(children:[SizedBox(width:380,child:list),const VerticalDivider(width:1),Expanded(child:policy==null?const _Empty('Select a policy pack'):ListView(padding:const EdgeInsets.all(24),children:[Text(policy.name,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:8),Text('Version ${policy.version}'),const SizedBox(height:12),FilledButton.icon(onPressed:c.mutating?null:()=>c.setPolicyActive(policy.id,active:!policy.active),icon:Icon(policy.active?Icons.archive_outlined:Icons.verified_outlined),label:Text(policy.active?'Archive policy':'Activate policy')),const Divider(height:32),Text('Policy rules',style:Theme.of(context).textTheme.titleMedium),...policy.rules.map((rule)=>ListTile(leading:const Icon(Icons.rule),title:Text(rule)))]))]);
  });
  Widget _market(GovernanceController c,GovernanceSnapshot s)=>ListView(padding:const EdgeInsets.all(16),children:[if(s.marketplace.isEmpty)const _Empty('Marketplace is empty')else...s.marketplace.map((x)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(x.name,style:Theme.of(context).textTheme.titleMedium)),if(x.verified)const Icon(Icons.verified,color:Colors.teal)]),Text('${x.kind} · v${x.version}'),Wrap(spacing:6,children:x.permissions.map((p)=>Chip(label:Text(p))).toList()),Align(alignment:AlignmentDirectional.centerEnd,child:x.installed?OutlinedButton(onPressed:()=>c.uninstall(x.id),child:const Text('Uninstall')):FilledButton(onPressed:()=>c.install(x.id),child:const Text('Install')))]))))]);
  Widget _routing(GovernanceController c,GovernanceSnapshot s)=>ListView(padding:const EdgeInsets.all(16),children:[_metrics([('Regions','${s.operations.activeRegions}'),('Healthy','${s.operations.healthyTargets}'),('Degraded','${s.operations.degradedTargets}'),('Failover',s.operations.failoverReady?'Ready':'Pending')]),const SizedBox(height:12),...s.targets.map((x)=>Card(child:ListTile(leading:const Icon(Icons.route),title:Text('${x.region} · ${x.provider}/${x.model}'),subtitle:Text('${x.latencyMs} ms · \$${x.cost}/1k tokens'),trailing:PopupMenuButton<String>(onSelected:(status)=>c.updateTarget(RoutingTarget(id:x.id,region:x.region,provider:x.provider,model:x.model,status:status,latencyMs:x.latencyMs,cost:x.cost,modalities:x.modalities,sensitivity:x.sensitivity)),itemBuilder:(_)=>const[PopupMenuItem(value:'healthy',child:Text('Mark healthy')),PopupMenuItem(value:'degraded',child:Text('Mark degraded')),PopupMenuItem(value:'disabled',child:Text('Disable'))]))))]);
  Widget _metrics(List<(String,String)> values)=>GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),childAspectRatio:2,children:values.map((x)=>Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.$2,style:Theme.of(context).textTheme.titleLarge),Text(x.$1)])))).toList());
}
class _Banner extends StatelessWidget{const _Banner(this.text);final String text;@override Widget build(BuildContext context)=>Material(color:Theme.of(context).colorScheme.errorContainer,child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[const Icon(Icons.cloud_off),const SizedBox(width:8),Expanded(child:Text(text))])));}
class _Empty extends StatelessWidget{const _Empty(this.text);final String text;@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.all(40),child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.inbox_outlined,size:40),const SizedBox(height:8),Text(text)])));}
